spring:
  application:
    name: companyService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 4795895q
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

userapi:
  getCompanyStatusUrl: http://localhost:8083/users

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI:true}
  api-docs:
    enabled: ${SWAGGER_API_DOCS:true}

